// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/library.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type CreateBookRequest struct {
	Book                 *Book    `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{1}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type ListBookRequest struct {
	PageToken            string   `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBookRequest) Reset()         { *m = ListBookRequest{} }
func (m *ListBookRequest) String() string { return proto.CompactTextString(m) }
func (*ListBookRequest) ProtoMessage()    {}
func (*ListBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{2}
}

func (m *ListBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBookRequest.Unmarshal(m, b)
}
func (m *ListBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBookRequest.Marshal(b, m, deterministic)
}
func (m *ListBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBookRequest.Merge(m, src)
}
func (m *ListBookRequest) XXX_Size() int {
	return xxx_messageInfo_ListBookRequest.Size(m)
}
func (m *ListBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBookRequest proto.InternalMessageInfo

func (m *ListBookRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListBookRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListBookResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBookResponse) Reset()         { *m = ListBookResponse{} }
func (m *ListBookResponse) String() string { return proto.CompactTextString(m) }
func (*ListBookResponse) ProtoMessage()    {}
func (*ListBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{3}
}

func (m *ListBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBookResponse.Unmarshal(m, b)
}
func (m *ListBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBookResponse.Marshal(b, m, deterministic)
}
func (m *ListBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBookResponse.Merge(m, src)
}
func (m *ListBookResponse) XXX_Size() int {
	return xxx_messageInfo_ListBookResponse.Size(m)
}
func (m *ListBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBookResponse proto.InternalMessageInfo

func (m *ListBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *ListBookResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "nokamoto.github.com.example.library.Book")
	proto.RegisterType((*CreateBookRequest)(nil), "nokamoto.github.com.example.library.CreateBookRequest")
	proto.RegisterType((*ListBookRequest)(nil), "nokamoto.github.com.example.library.ListBookRequest")
	proto.RegisterType((*ListBookResponse)(nil), "nokamoto.github.com.example.library.ListBookResponse")
}

func init() {
	proto.RegisterFile("api/library.proto", fileDescriptor_23dfc8515c58d0b2)
}

var fileDescriptor_23dfc8515c58d0b2 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4d, 0x4f, 0xf2, 0x40,
	0x14, 0x85, 0xd3, 0xf7, 0x05, 0x85, 0x8b, 0x06, 0x99, 0x15, 0xc1, 0x98, 0x60, 0x4d, 0x8c, 0xc4,
	0x30, 0x4d, 0xf0, 0x63, 0x47, 0x4c, 0x70, 0x8b, 0xc6, 0x54, 0x57, 0x6e, 0x9a, 0x29, 0xde, 0xe0,
	0xa4, 0xb4, 0x77, 0xec, 0x0c, 0xf2, 0xe1, 0xcf, 0xf6, 0x0f, 0x98, 0x4e, 0x21, 0x10, 0xdd, 0x94,
	0x5d, 0x7b, 0xee, 0x3d, 0xe7, 0x3e, 0x3d, 0x29, 0x34, 0x84, 0x92, 0xde, 0x44, 0x86, 0xa9, 0x48,
	0x17, 0x5c, 0xa5, 0x64, 0x88, 0x9d, 0x25, 0x14, 0x89, 0x98, 0x0c, 0xf1, 0xb1, 0x34, 0xef, 0xd3,
	0x90, 0x8f, 0x28, 0xe6, 0x38, 0x17, 0xb1, 0x9a, 0x20, 0x5f, 0xad, 0xba, 0x7d, 0x28, 0x0d, 0x88,
	0x22, 0xc6, 0xa0, 0x94, 0x88, 0x18, 0x9b, 0x4e, 0xdb, 0xb9, 0xa8, 0xfa, 0xf6, 0x99, 0x9d, 0xc2,
	0xc1, 0x9b, 0xd4, 0x6a, 0x22, 0x16, 0x81, 0x9d, 0xfd, 0xb3, 0xb3, 0xda, 0x4a, 0x7b, 0x14, 0x31,
	0xba, 0x3e, 0x34, 0xee, 0x53, 0x14, 0x06, 0xb3, 0x10, 0x1f, 0x3f, 0xa6, 0xa8, 0x0d, 0xeb, 0x43,
	0x29, 0x24, 0x8a, 0xec, 0x7e, 0xad, 0xd7, 0xe1, 0x05, 0x38, 0xb8, 0xf5, 0x5b, 0x9b, 0xfb, 0x00,
	0xf5, 0xa1, 0xd4, 0x66, 0x3b, 0xf1, 0x04, 0x40, 0x89, 0x31, 0x06, 0x86, 0x22, 0x4c, 0x56, 0x8c,
	0xd5, 0x4c, 0x79, 0xc9, 0x04, 0x76, 0x0c, 0xf6, 0x25, 0xd0, 0x72, 0x99, 0x53, 0x96, 0xfd, 0x4a,
	0x26, 0x3c, 0xcb, 0x25, 0xba, 0x5f, 0x70, 0xb4, 0x89, 0xd3, 0x8a, 0x12, 0x8d, 0xec, 0x0e, 0xca,
	0xd9, 0x29, 0xdd, 0x74, 0xda, 0xff, 0x77, 0x43, 0xcc, 0x7d, 0xec, 0x1c, 0xea, 0x09, 0xce, 0x4d,
	0xb0, 0x45, 0x95, 0xb7, 0x73, 0x98, 0xc9, 0x4f, 0x6b, 0xb2, 0xde, 0xb7, 0x03, 0xfb, 0xc3, 0xdc,
	0xcf, 0x08, 0x60, 0xd3, 0x15, 0xbb, 0x2d, 0x74, 0xf3, 0x4f, 0xb9, 0xad, 0xe2, 0xac, 0x6c, 0x06,
	0x95, 0xf5, 0x97, 0xb3, 0xeb, 0x42, 0xb6, 0x5f, 0xbd, 0xb7, 0x6e, 0x76, 0x74, 0xe5, 0xf5, 0x0e,
	0x2e, 0x5f, 0x3b, 0x9b, 0x75, 0x6f, 0x1d, 0xe1, 0x8d, 0x53, 0x35, 0x9a, 0x61, 0xd8, 0x4d, 0x51,
	0x8c, 0x4c, 0xf7, 0x73, 0x8a, 0x9e, 0x50, 0x32, 0xdc, 0xb3, 0x7f, 0xeb, 0xd5, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x0e, 0x02, 0x53, 0x61, 0xc2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LibraryClient is the client API for Library service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryClient interface {
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error)
	ListBook(ctx context.Context, in *ListBookRequest, opts ...grpc.CallOption) (*ListBookResponse, error)
}

type libraryClient struct {
	cc grpc.ClientConnInterface
}

func NewLibraryClient(cc grpc.ClientConnInterface) LibraryClient {
	return &libraryClient{cc}
}

func (c *libraryClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/nokamoto.github.com.example.library.Library/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) ListBook(ctx context.Context, in *ListBookRequest, opts ...grpc.CallOption) (*ListBookResponse, error) {
	out := new(ListBookResponse)
	err := c.cc.Invoke(ctx, "/nokamoto.github.com.example.library.Library/ListBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryServer is the server API for Library service.
type LibraryServer interface {
	CreateBook(context.Context, *CreateBookRequest) (*Book, error)
	ListBook(context.Context, *ListBookRequest) (*ListBookResponse, error)
}

// UnimplementedLibraryServer can be embedded to have forward compatible implementations.
type UnimplementedLibraryServer struct {
}

func (*UnimplementedLibraryServer) CreateBook(ctx context.Context, req *CreateBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (*UnimplementedLibraryServer) ListBook(ctx context.Context, req *ListBookRequest) (*ListBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBook not implemented")
}

func RegisterLibraryServer(s *grpc.Server, srv LibraryServer) {
	s.RegisterService(&_Library_serviceDesc, srv)
}

func _Library_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nokamoto.github.com.example.library.Library/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_ListBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).ListBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nokamoto.github.com.example.library.Library/ListBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).ListBook(ctx, req.(*ListBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Library_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nokamoto.github.com.example.library.Library",
	HandlerType: (*LibraryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _Library_CreateBook_Handler,
		},
		{
			MethodName: "ListBook",
			Handler:    _Library_ListBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/library.proto",
}
